// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-xSAawFQOQeN9D3TR0_xCfzlhWsJa9cc',
    appId: '1:521426592348:web:f1e8b2c56b841befedbc99',
    messagingSenderId: '521426592348',
    projectId: 'donow-27b39',
    authDomain: 'donow-27b39.firebaseapp.com',
    storageBucket: 'donow-27b39.firebasestorage.app',
    measurementId: 'G-8RCF7CJNJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXePsMJqarJaqp4F22ZWZqh3Qtoy8gUMw',
    appId: '1:521426592348:android:e0809ef2b8a525f3edbc99',
    messagingSenderId: '521426592348',
    projectId: 'donow-27b39',
    storageBucket: 'donow-27b39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChv467bnCyz_TpgaBZnyqfhBCXabFHFIU',
    appId: '1:521426592348:ios:5407ab8f559c4935edbc99',
    messagingSenderId: '521426592348',
    projectId: 'donow-27b39',
    storageBucket: 'donow-27b39.firebasestorage.app',
    iosBundleId: 'com.donow.cpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChv467bnCyz_TpgaBZnyqfhBCXabFHFIU',
    appId: '1:521426592348:ios:12f3e0d27d45c838edbc99',
    messagingSenderId: '521426592348',
    projectId: 'donow-27b39',
    storageBucket: 'donow-27b39.firebasestorage.app',
    iosBundleId: 'com.atomictask.doNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-xSAawFQOQeN9D3TR0_xCfzlhWsJa9cc',
    appId: '1:521426592348:web:6144459b13eb9bfbedbc99',
    messagingSenderId: '521426592348',
    projectId: 'donow-27b39',
    authDomain: 'donow-27b39.firebaseapp.com',
    storageBucket: 'donow-27b39.firebasestorage.app',
    measurementId: 'G-X36MRG43MS',
  );
}
