name: Runner
options:
  bundleIdPrefix: com.donow
  deploymentTarget:
    iOS: 16.2

configs:
  Debug: debug
  Release: release

settings:
  base:
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: "NO"
    IPHONEOS_DEPLOYMENT_TARGET: 16.2

targets:
  Runner:
    type: application
    platform: iOS
    sources: 
      - Runner
      - Flutter
      - path: DoNowWidget/DoNowActivityAttributes.swift
        group: Shared
    configFiles:
      Debug: Flutter/Debug.xcconfig
      Release: Flutter/Release.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.donow.app
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Runner/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: 
          - "$(inherited)"
          - "@executable_path/Frameworks"
        CODE_SIGN_ENTITLEMENTS: Runner/Runner.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: Runner/Runner-Bridging-Header.h
        SWIFT_VERSION: 5.0
    entitlements:
      path: Runner/Runner.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.donow.app
    dependencies:
      - target: DoNowWidget
        embed: true
        link: false
    preBuildScripts:
      - script: /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
        name: Run Flutter Build Script
    postBuildScripts:
      - script: /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
        name: Embed Flutter Framework

  RunnerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - RunnerTests
    configFiles:
      Debug: Flutter/Debug.xcconfig
      Release: Flutter/Release.xcconfig
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Runner.app/Runner"
    dependencies:
      - target: Runner

  DoNowWidget:
    type: app-extension
    platform: iOS
    sources: DoNowWidget
    # NO configFiles here - this is a pure Swift extension, NOT a Flutter target
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.donow.app.widget
        INFOPLIST_FILE: DoNowWidget/Info.plist
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SKIP_INSTALL: NO
        CODE_SIGN_ENTITLEMENTS: DoNowWidget/DoNowWidget.entitlements
        SWIFT_VERSION: 5.0
        # Ensure widget doesn't try to link Flutter
        OTHER_LDFLAGS: ""
    entitlements:
      path: DoNowWidget/DoNowWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.donow.app
