name: Runner
options:
  bundleIdPrefix: com.donow
  deploymentTarget:
    iOS: 16.2

settings:
  base:
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_ENTITLEMENTS: ""
    IPHONEOS_DEPLOYMENT_TARGET: 16.2

targets:
  Runner:
    type: application
    platform: iOS
    sources: 
      - Runner
      - Flutter
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.donow.app
        INFOPLIST_FILE: Runner/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: 
          - "$(inherited)"
          - "@executable_path/Frameworks"
        CODE_SIGN_ENTITLEMENTS: Runner/Runner.entitlements
    entitlements:
      path: Runner/Runner.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.donow.app
    dependencies:
      - target: DoNowWidget
    preBuildScripts:
      - script: /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
        name: Run Flutter Build Script
    postBuildScripts:
      - script: /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
        name: Embed Flutter Framework

  RunnerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - RunnerTests
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Runner.app/Runner"
    dependencies:
      - target: Runner

  DoNowWidget:
    type: app-extension
    platform: iOS
    sources: DoNowWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.donow.app.widget
        INFOPLIST_FILE: DoNowWidget/Info.plist
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SKIP_INSTALL: NO
        CODE_SIGN_ENTITLEMENTS: DoNowWidget/DoNowWidget.entitlements
        SWIFT_VERSION: 5.0
    entitlements:
      path: DoNowWidget/DoNowWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.donow.app
